# `📅DAY_01` _데이터분석 및 시각화

## 데이터 시각화

### 시각화

데이터를 숫자나 글자로 보는 대신, 그래프나 그림으로 만들어 쉽게 이해할 수 있도록 보여주는 것.

- 시각화가 필요한 이유 : **한 눈에 쉽게 문제를 발견하기 위해서**

#### 대표적인 종류

1. 막대 그래프(Bar Chart)
2. 꺾은선 그래프(Line Chart)
3. 원 그래프(Pie Chart)
4. 히스토그램(Histogram)
5. 산점도(Scatter Plot)

#### 반도체 공정에서의 시각화

- **온도 데이터**를 그래프로 그리면, 갑자기 온도가 올라가거나 내려간 부분을 금방 찾을 수 있음.
- **웨이퍼 두께**를 그래프로 그리면, 두께가 갑자기 얇아지거나 두꺼워진 부분을 한눈에 볼 수 있음.
- **불량률 데이터**를 그림으로 표현하면, 어느 부분에서 문제라 자주 발생하는지 쉽게 확인할 수 있음.

In [2]:
# 03_cafe_1.csv
# 어떤 카페에서 두 달 동안 판매한 음료와 케이크의 하루 판매량을 기록한 표

import pandas as pd

df = pd.read_csv('03_cafe_1.csv')
df.head()

,date,day_of_week,americano,cafe_latte,cappuccino,lemon_ade,grapefruit_ade,herbal_tea,chocolate_cake,ny_cheese_cake,carrot_cake,tiramisu
0,2025-01-01,수,218.0,68.0,78,62.0,82,67,0,8,7,9
1,2025-01-02,목,222.0,79.0,105,52.0,44,54,23,31,0,6
2,2025-01-03,금,215.0,30.0,94,45.0,103,62,25,0,8,12
3,2025-01-04,토,313.0,100.0,106,86.0,106,94,22,66,78,47
4,2025-01-05,일,311.0,82.0,137,101.0,89,70,36,35,40,17

In [3]:
# 기본 정보 확인

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            60 non-null     object
 1   day_of_week     60 non-null     object
 2   americano       58 non-null     float64
 3   cafe_latte      59 non-null     float64
 4   cappuccino      60 non-null     int64
 5   lemon_ade       59 non-null     float64
 6   grapefruit_ade  60 non-null     int64
 7   herbal_tea      60 non-null     int64
 8   chocolate_cake  60 non-null     int64
 9   ny_cheese_cake  60 non-null     int64
 10  carrot_cake     60 non-null     int64
 11  tiramisu        60 non-null     int64
dtypes: float64(3), int64(7), object(2)
memory usage: 5.8+ KB

In [4]:
# 데이터 요약

df.describe()

,americano,cafe_latte,cappuccino,lemon_ade,grapefruit_ade,herbal_tea,chocolate_cake,ny_cheese_cake,carrot_cake,tiramisu
count,58.000000,59.000000,60.000000,59.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,250.620690,80.084746,99.583333,60.406780,79.033333,68.116667,31.183333,24.116667,24.516667,24.850000
std,66.880052,22.978467,18.723041,21.094303,25.909207,16.854403,21.496938,22.222367,18.587851,20.988152
min,20.000000,30.000000,56.000000,18.000000,25.000000,33.000000,0.000000,0.000000,0.000000,0.000000
25%,218.000000,66.500000,86.500000,46.500000,62.500000,55.750000,16.500000,5.750000,8.000000,9.750000
50%,222.500000,77.000000,100.500000,57.000000,80.500000,67.000000,29.000000,21.000000,23.500000,21.000000
75%,309.000000,91.000000,109.250000,74.000000,96.000000,81.250000,46.250000,36.500000,38.250000,37.500000
max,500.000000,144.000000,148.000000,106.000000,145.000000,109.000000,102.000000,80.000000,78.000000,100.000000